version: '3.8'

networks:
  profile-api:
    name: profile-api

services:
  adminer:
    image: adminer
    container_name: profile-api-adminer
    networks:
      - profile-api
    environment:
      ADMINER_PLUGINS: tables-filter tinymce
      ADMINER_DESIGN: lucas-sandery
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    container_name: profile-api-postgres
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    networks:
      - profile-api
    volumes:
      - ../runtime/postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - ${PSQL_PORT}:5432
